parameters:
    ant.social_rest.form_factory.profile.class.default: Ant\SocialRestBundle\FormFactory\ProfileFormFactory
    ant.social_rest.form_type.profile.class.default: Ant\SocialRestBundle\FormType\ProfileFormType
    ant.social_rest.profile.form_name: ant_social_rest_profile

services:
    ant.social_rest.form_factory.profile:
        class: %ant.social_rest.form_factory.profile.class.default%
        arguments: [@form.factory, @ant.social_rest.form_type.profile, %ant.social_rest.profile.form_name%]
    ant.social_rest.form_type.profile:
        class: %ant.social_rest.form_type.profile.class.default%
        arguments: [%ant.social_rest.model.profile.class%]
        tags:
            - { name: form.type , alias: %ant.social_rest.profile.form_name% }