parameters:
    ant.social.entity_manager.visit_manager.class: Ant\SocialBundle\EntityManager\VisitManager
    ant.social.model.visit.class: Ant\SocialBundle\Entity\Visit
    ant.social.entity_manager.profile_manager.class: Ant\SocialBundle\EntityManager\ProfileManager
    ant.social.model.profile.class: Ant\SocialBundle\Entity\Profile
    
services:
    ant.social.manager.visit:
        class: %ant.social.entity_manager.visit_manager.class%
        arguments: [@doctrine.orm.entity_manager, %ant.social.model.visit.class%] 
    ant.social.manager.profile:
        class: %ant.social.entity_manager.profile_manager.class%
        arguments: [@doctrine.orm.entity_manager, %ant.social.model.profile.class%]