ant_social_rest_profile_create:
    pattern: /profiles
    defaults: { _controller: AntSocialRestBundle:Profile:create }
    methods: [POST]
ant_social_rest_profile_show:
    pattern: /profiles/{id}
    defaults: { _controller: AntSocialRestBundle:Profile:show }
    methods: [GET]