ant_social_rest_profile_create:
    pattern: /users/{id}/profiles
    defaults: { _controller: AntSocialRestBundle:Profile:create }
    methods: [POST, OPTIONS]
ant_social_rest_profile_show:
    pattern: /users/{id}/profiles
    defaults: { _controller: AntSocialRestBundle:Profile:show }
    methods: [GET]
ant_social_rest_profile_add_visit:
    pattern: /users/{id}/profiles/visits
    defaults: { _controller: AntSocialRestBundle:Profile:addVisit }
    methods: [POST]
ant_social_rest_profile_update_put:
    pattern: /users/{id}/profiles
    defaults: { _controller: AntSocialRestBundle:Profile:update }
    methods: [PUT, OPTIONS]
ant_social_rest_profile_update_patch:
    pattern: /users/{id}/profiles
    defaults: { _controller: AntSocialRestBundle:Profile:update }
    methods: [PATCH, OPTIONS]
ant_social_rest_profile_visitors:
    pattern: /users/{id}/visitors
    defaults: { _controller: AntSocialRestBundle:Visit:visitors }
    methods: [GET]

ant_social_rest_profile_voyeur:
    pattern: /users/{id}/voyeur
    defaults: { _controller: AntSocialRestBundle:Visit:voyeur }
    methods: [GET]